apiVersion: v1
kind: Service
metadata:
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ include "vlmcsd.fullname" . }}
  labels:
    app: {{ include "vlmcsd.name" . }}
    chart: {{ include "vlmcsd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: vlmcs
      protocol: TCP
      name: vlmcs
  selector:
    app: {{ include "vlmcsd.name" . }}
    release: {{ .Release.Name }}
